- name: Install BorgBackup
  hosts: all
  remote_user: root
  #remote_user: debian
  #become: yes

  # NOTE: due to race conditions, it is better not to run this playbook in parallel.
  # See roles/borg/tasks/pubkey.yaml
  serial: 1

  vars:
    - borg_passphrase: CHANGE_ME
    - borg_host_user: username
    - borg_host_addr: backup.example.org
    # SSH host key of backup host. This can be obtained by "ssh-keyscan".
    - borg_host_key: "backup.example.org ssh-ed25519 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

  roles:
    - role: borg
