- name: Download Borg binary
  get_url:
    url: "{{ borg_url }}"
    checksum: "{{ borg_checksum }}"
    dest: "{{ borg_path }}"
    mode: 0755

- name: Fix broken Python
  apt:
    name: python3-venv
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

- name: Create Borgmatic venv
  command: "python3 -m venv {{ borgmatic_dir }}"
  args:
    creates: "{{ borgmatic_dir }}/bin/pip"

- name: Install Borgmatic into venv
  pip:
    name: borgmatic
    version: "{{ borgmatic_version }}"
    executable: "{{ borgmatic_dir }}/bin/pip"

- name: Create Borgmatic config dir
  file:
    path: /etc/borgmatic
    state: directory

- name: Create Borgmatic excludes file
  command: touch /etc/borgmatic/excludes
  args:
    creates: /etc/borgmatic/excludes
    warn: no

- name: Render Borgmatic config
  template:
    src: borgmatic-config.yaml.j2
    dest: /etc/borgmatic/config.yaml
    mode: 0600

- name: Render Borgmatic systemd units
  template:
    src: "{{ item }}.j2"
    dest: "/etc/systemd/system/{{ item }}"
  with_items:
    - borgmatic.service
    - borgmatic.timer

- name: Enable Borgmatic systemd timer
  systemd:
    name: borgmatic.timer
    state: started
    enabled: yes
    daemon_reload: yes

- import_tasks: pubkey.yaml
  when: borg_setup_pubkey
